name: Test Rust

on:
  push:
    branches: ["main"]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@e2a55d2ffb04f378e9626c28d38b36d230d1e12f # stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
      - name: Fmt Check
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --no-deps -- -Dwarnings
      - name: Compile
        run: cargo build
      - name: Test
        run: cargo test
