name: Rust

on:
  push:
    branches: ["main"]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Fmt Check
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --no-deps -- -Dwarnings
      - name: Compile
        run: cargo build
      - name: Test
        run: cargo test
